/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreatePublisherArgs } from "./CreatePublisherArgs";
import { UpdatePublisherArgs } from "./UpdatePublisherArgs";
import { DeletePublisherArgs } from "./DeletePublisherArgs";
import { PublisherFindManyArgs } from "./PublisherFindManyArgs";
import { PublisherFindUniqueArgs } from "./PublisherFindUniqueArgs";
import { Publisher } from "./Publisher";
import { PublisherService } from "../publisher.service";

@graphql.Resolver(() => Publisher)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class PublisherResolverBase {
  constructor(
    protected readonly service: PublisherService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Publisher",
    action: "read",
    possession: "any",
  })
  async _publishersMeta(
    @graphql.Args() args: PublisherFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Publisher])
  @nestAccessControl.UseRoles({
    resource: "Publisher",
    action: "read",
    possession: "any",
  })
  async publishers(
    @graphql.Args() args: PublisherFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Publisher[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Publisher",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Publisher, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Publisher",
    action: "read",
    possession: "own",
  })
  async publisher(
    @graphql.Args() args: PublisherFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Publisher | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Publisher",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Publisher)
  @nestAccessControl.UseRoles({
    resource: "Publisher",
    action: "create",
    possession: "any",
  })
  async createPublisher(
    @graphql.Args() args: CreatePublisherArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Publisher> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Publisher",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Publisher"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Publisher)
  @nestAccessControl.UseRoles({
    resource: "Publisher",
    action: "update",
    possession: "any",
  })
  async updatePublisher(
    @graphql.Args() args: UpdatePublisherArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Publisher | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Publisher",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Publisher"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Publisher)
  @nestAccessControl.UseRoles({
    resource: "Publisher",
    action: "delete",
    possession: "any",
  })
  async deletePublisher(
    @graphql.Args() args: DeletePublisherArgs
  ): Promise<Publisher | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
